### ISSUE TITLE
Misspelling in $MenuOptions: 'seperator' should be 'separator'

### ISSUE THREAD

**Issue by joeskeen** [bibistroc/powershell-interactive-menu#1]
This should be an easy fix, although you would probably want to keep both as valid for now for backwards compatibility

**Comment by bibistroc** [comment]
Thanks for the interest in the project and for the finding. I fixed the typo in commit f2ad00e2fc37de6c35783895424ba441a624efca and published a new version on PowerShell Gallery ([v0.4](https://www.powershellgallery.com/packages/InteractiveMenu/0.4)).
